### ISSUE TITLE
Why do we need an end date?

### ISSUE THREAD

**Issue by mewing0328** [VenBak/PlayDate#103]
Are play dates expected to span more than one day? 
Typically, play dates are "Hey lets meet on 3/15 at 4pm at xyz park!"

**Comment by mewing0328** [comment]
@smithm4949 If you are good with changing below, please let Claire & I know - we will take care of FRONT END
for BACK END, it would be to change for Events Start Date to just simply "Date" and then removing end date
BACK END CHANGE: 
- seeds
- model

@leeclaire156 @mewing0328 
FRONT END CHANGE: 
- the JS for add events (post and validations)
- the JS for edit events (put and validations)
- the add events form
- the edit events form

**Comment by leeclaire156** [comment]
resolved!!
