### ISSUE TITLE
event and owner missing link

### ISSUE THREAD

**Issue by leeclaire156** [VenBak/PlayDate#42]
Associated events for owner do not show. I set the event.host_id == owner.id and while they will show in MySQL when joining models, they will not appear on the localhost side. The returned object is the correct host but the associated events object is empty.

**Comment by leeclaire156** [comment]
For some reason each sign up is linked to this one event I made?

**Comment by smithm4949** [comment]
Leaving this open for now but I think this was solved with the change I just made to fix claires issue when rendering the events page
