### ISSUE TITLE
Add validation/hints for frontend

### ISSUE THREAD

**Issue by smithm4949** [VenBak/PlayDate#64]
Validate inputs from forms before sending to the backend

Tell the user what requirements they need to pass before we 'bad request' them

Ex: password has to between 8 and 16 characters

See https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation#using_built-in_form_validation

**Comment by mewing0328** [comment]
Zip code for new event needs to have a validation for 5 digits

**Comment by leeclaire156** [comment]
sign up validation complete, we just need to change the alert responses but I'll leave that to y'all for testing purposes

**Comment by leeclaire156** [comment]
validations complete, need to add one for time tho.
