### ISSUE TITLE
Date field should include date and time

### ISSUE THREAD

**Issue by smithm4949** [VenBak/PlayDate#67]
Users should be able to say they are starting an event at 2pm and ending at 4pm

NOTE: although the date field is stored a date/time object, it can be created/parsed however we want on the frontend.

We could have 1 field for "date" and 2 additional fields for "start time" and "end time." Then, before sending to the backend, create two new Date() objects using the given 'date' and the times to create a start datetime object and an end datetime object

**Comment by mewing0328** [comment]
Was completed in Issue #80
