### ISSUE TITLE
Add Time to Events Model

### ISSUE THREAD

**Issue by mewing0328** [VenBak/PlayDate#80]
@smithm4949 
Back End
1. Add a time column to Events model
2. Edit seed data for events with time

@leeclaire156 @mewing0328 
Front End
1. Render of events handlebars, add time
2. Edit of events handlebars, add time 
3. JS of events for edit, add time

**Comment by smithm4949** [comment]
Backend changes made in most recent PR from myles

**Comment by mewing0328** [comment]
Front end changes made and tested successfully
